### ISSUE TITLE
Transcribe CCLP table

### ISSUE THREAD

**Issue by fiatflux** [BoulderCRC/BoulderCRC.github.io#15]
The table with the yellow heading in manual/issues should be stuck into a pretty HTML table.

**Comment by fiatflux** [comment]
Travis typed this for us and sent it by email. :-D

<table class="columnHeader"> <thead> <tr> <th></th> <th>Monthly</th> <th>Annual (12-mo)</th> </tr> </thead> <tbody> <tr> <td>Transportation</td> <td>$348</td> <td>$4,171</td> </tr> <tr> <td>Housing</td> <td>$1,241</td> <td>$14,889</td> </tr> <tr> <td>Food</td> <td>$368</td> <td>$4,410</td> </tr> <tr> <td>Medical</td> <td>$182</td> <td>$2,183</td> </tr> <tr> <td>Miscellaneous</td> <td>$214</td> <td>$2,571</td> </tr> <tr> <td>Books/Supplies</td> <td>$200</td> <td>$1,800 (9-mo)</td> </tr> <tr> <td>Mandatory Fees</td> <td>$197</td> <td>$1,776 (9-mo)</td> </tr> <tr> <td>Total</td> <td>$2,749</td> <td>$31,800</td> </tr> </tbody> </table>

**Comment by koscida** [comment]
Table has been added to the living wage page.
